default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  database: address_book_development
test:
  <<: *default
  database: address_book_test
production:
  <<: *default
  database: address_book_production
  username: address_book
  password: <%= ENV['ADDRESS_BOOK_DATABASE_PASSWORD'] %>
